FROM node:latest

MAINTAINER Kanstantsin Kamkou <kkamkou@gmail.com>

RUN npm install -g bower ember-cli ember-cli-babel babel-preset-es2015 phantomjs

ENV NODE_PATH /usr/local/lib/node_modules

WORKDIR /opt

VOLUME ["/opt"]

EXPOSE 4200 49152
